name: Update Snapshot Version After Release

on:
  release:
    types: [published]

jobs:
  update-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Calculate next snapshot version
        id: next-version
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          echo "Release tag: $RELEASE_TAG"
          
          # Remove 'v' prefix if present (e.g., v0.0.1 -> 0.0.1)
          VERSION=${RELEASE_TAG#v}
          
          # Split version into parts (e.g., 0.0.1 -> 0 0 1)
          IFS='.' read -ra PARTS <<< "$VERSION"
          MAJOR=${PARTS[0]}
          MINOR=${PARTS[1]}
          PATCH=${PARTS[2]}
          
          # Increment patch version for next snapshot
          NEXT_PATCH=$((PATCH + 1))
          NEXT_VERSION="$MAJOR.$MINOR.$NEXT_PATCH-SNAPSHOT"
          
          echo "Next snapshot version: $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
      
      - name: Update pom.xml version
        run: |
          mvn versions:set -DnewVersion=${{ steps.next-version.outputs.next_version }}
          mvn versions:commit
      
      - name: Update README.md
        run: |
          NEXT_VERSION="${{ steps.next-version.outputs.next_version }}"
          sed -i "s/<version>.*-SNAPSHOT<\/version>/<version>$NEXT_VERSION<\/version>/g" README.md
          sed -i "s/igrf-model:.*-SNAPSHOT'/igrf-model:$NEXT_VERSION'/g" README.md
          sed -i "s/\*\*Version .*-SNAPSHOT\*\*/\*\*Version $NEXT_VERSION\*\*/g" README.md
      
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump snapshot version to ${{ steps.next-version.outputs.next_version }}"
          branch: snapshot-version-update
          delete-branch: true
          title: "Bump snapshot version to ${{ steps.next-version.outputs.next_version }}"
          body: |
            Automatically generated PR to update snapshot version after release ${{ github.event.release.tag_name }}.
            
            Changes:
            - Updated pom.xml version to ${{ steps.next-version.outputs.next_version }}
            - Updated README.md with new snapshot version
          labels: automated
      
      - name: Approve and Merge PR
        if: steps.create-pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Created PR #$PR_NUMBER"
          
          # Wait a moment for PR to be fully created
          sleep 5
          
          # Approve the PR
          gh pr review $PR_NUMBER --approve --body "Auto-approving snapshot version update"
          
          # Merge the PR
          gh pr merge $PR_NUMBER --auto --squash --delete-branch
